name: RangeTest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Running tests
      run: |
        echo Starting the tests:
        javac -cp lib/jcommon-1.0.17.jar:lib/javax.servlet-api-3.0.1.jar:lib/xml-apis-1.4.01.jar:src/ -d bin/ $(find src/ -name "*.java")
        javac -d bin -cp bin:lib/junit-platform-console-standalone-1.5.2.jar test/*
        java -jar lib/junit-platform-console-standalone-1.5.2.jar --class-path bin --scan-class-path
